name: deploy-to-ec2

# Trigger manually
on:
  workflow_dispatch

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo apt update -y
            sudo apt upgrade -y
            sudo apt install -y apache2
            sudo apt install -y git
            sudo apt install -y php
            sudo apt install -y php-mysqlnd
            cd /var/www/html/
            sudo git clone https://github.com/mtuason-bvc/2024-CLCM3102-group1
            sudo systemctl start apache2
            sudo systemctl status apache2